### ISSUE TITLE
[Entrega #1] Análise Exploratória de Dados

### ISSUE THREAD

**Issue by carlos-stefano** [atlantico-academy/equipe2-2024.3#3]
Criar um notebook de análise exploratória `notebooks/01-exploratory_data_analysis.ipynb`, contendo as seguintes seções de texto:

 - [x] **Descrição dos dados**: informações sobre a quantidade de instâncias, variáveis e seus tipos, quantidade de valores faltantes. Utilize o dicionário de dados nessa seção.
 - [x]  **Perguntas de partida e hipóteses**: que tipo de informações podem ser obtidas a partir dos dados e quais hipóteses podem ser levantadas?
 - [x]  **Insights**: respostas às perguntas feitas na seção anterior e quais informações interessantes podem ser levantadas através dos dados?

**Comment by HalaneMoreira** [comment]
Finalizado!
